### ISSUE TITLE
some stuff I noticed in the playtest

### ISSUE THREAD

**Issue by Merlin1230** [polygoblyn/MonkeStation#35]
- You can spam fart on a bible which makes the sound effect get spamed. Probably want to change this, perhaps by stopping them from farting?
- The tapping signs thing makes them grow WAY TOO BIG. Should probably make it a smaller thing.
- Removing the boom boots with the anti-tamper thing and it blowing up works fine, just we MIGHT wanna somehow add a warning that you're gonna blow up.

**Comment by nednaZ** [comment]
I'll look into a way to stop biblefart spam and add some form of cap to the sign tapping. Decently large, but not screen filling.

**Comment by nednaZ** [comment]
Both of my issues here are now solved with PRs either committed or in waiting.

**Comment by Merlin1230** [comment]
Silly me forgeting to close this thing thats not relevant anymore!
